version: '3.9'

services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_app
    env_file: '.env'
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - database
  database:
    image: postgres:15.1
    container_name: todo_db
    logging:
      driver: none
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
