export enum ErrorCode {
  BAD_REQUEST = 'BAD_REQUEST',
  DATABASE = 'DATABASE',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  INTERNAL_SERVER = 'INTERNAL_SERVER',
  INVALID_DATA = 'INVALID_DATA',
}
